### ISSUE TITLE
Context class improvements

### ISSUE THREAD

**Issue by Hybanos** [PPN-microbench/PPN-microbench#1]
To be improved:
 - don't use grep, directly parse `/proc/*` for infos.
 - accurate cpu core to thread mapping

To be added:
 - number of sockets

**Comment by dssgabriel** [comment]
> [!TIP]
> You can use the following Markdown syntax for checking boxes and tracking the progress of the features:
> ```md
> - [x] implement this
> - [ ] implement that
> ```
Which renders as:
- [x] implement this
- [ ] implement that
