### ISSUE TITLE
CMake improvements

### ISSUE THREAD

**Issue by Corentin-Skyspirit** [PPN-microbench/PPN-microbench#9]
- [ ] Use modern CMake CLI syntax (examples in wiki https://github.com/PPN-microbench/PPN-microbench/wiki/Nov-20-2024)
- [ ] Use `FetchContent` for JSON library
- [ ] Remove clang-format from CMake
- [ ] Remove `file(GLOB_RECURSE ...)`
- [ ] Use `target_compile_options` instead of `CMAKE_CXX_FLAGS`
- [ ] Use `CMAKE_BUILD_TYPE`

**Comment by Hybanos** [comment]
CI won't work until we use fetchcontent for the json lib
